services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # LocalStack edge port
      - "4571:4571"   # (optional) legacy lambda port
    environment:
      - SERVICES=lambda,apigateway,dynamodb,sns,cloudformation,iam,logs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
